/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chem.UI;

import chem.core.ChemApp;
import chem.figures.persist.DocumentModel;
import chem.network.ConnectThread;
import chem.network.DocumentReceiver;
import chem.network.NetworkHandler;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.TableModel;

/**
 *
 * @author Mefi
 */
public class LoadDialog extends javax.swing.JDialog implements DocumentReceiver
{
    // This dialog sets parent's project name and id
    NetworkHandler m_networkhandler = null;
    ConnectThread m_conThread = null;
    private final ChemApp m_parent;
    
    List<DocumentModel> m_docModels = new ArrayList<>();
    
    DocumentModel m_selectedDoc = null;

    /**
     * Creates new form LoadDialog
     */
    public LoadDialog(java.awt.Frame parent, boolean modal, NetworkHandler networkHandler)
    {
        super(parent, modal);
        initComponents();
        
        m_parent = (ChemApp)parent;
        
        listEditableDocs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableViewableDocs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tableViewableDocs.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> 
        {
            m_selectedDoc = m_docModels.get(tableViewableDocs.getSelectedRow());
            lbl_SelectedDoc.setText(m_selectedDoc.getName() + " " + m_selectedDoc.getId());
        });
        
        m_conThread = new ConnectThread(networkHandler.getContext(), this);
    }
    
    public void startNetworking()
    {
        m_conThread.start();
    }
    
    //Helper method for loadProjects()
    public synchronized void displayResult()
    {
        cb_projects.removeAllItems();
        for (DocumentModel dm : m_docModels)
        {
            ComboBoxItem cbi = new ComboBoxItem(dm);
            cb_projects.addItem(cbi);
        }
        
        DefaultListModel model = new DefaultListModel();
        for (DocumentModel dm : m_docModels)
        {
            DocumentListItem dli = new DocumentListItem(dm);
            model.addElement(dli);
        }
        listEditableDocs.setModel(model);
        
        TableModel tableModel = new DocTableModel(m_docModels);
        tableViewableDocs.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_projects = new javax.swing.JComboBox();
        btn_cancel = new javax.swing.JButton();
        btn_Load = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEditableDocs = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnJoin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewableDocs = new javax.swing.JTable();
        lbl_SelectedDoc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pick project:");

        cb_projects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_Load.setText("Load");
        btn_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoadActionPerformed(evt);
            }
        });

        listEditableDocs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listEditableDocs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEditableDocsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listEditableDocs);

        jLabel2.setText("Editable Documents:");

        jLabel3.setText("Viewable Documents:");

        btnJoin.setText("Join");

        tableViewableDocs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableViewableDocs);

        lbl_SelectedDoc.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_projects, 0, 353, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                .addComponent(jScrollPane3))
                            .addComponent(lbl_SelectedDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Load, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_projects, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Load)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJoin))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(lbl_SelectedDoc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //LOAD - sets parents project name and id
    private void btn_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoadActionPerformed
        
        if (m_selectedDoc != null)
        {
            m_parent.loadDocument(m_selectedDoc.getId());
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btn_LoadActionPerformed

    //CANCEL - closes dialog
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void listEditableDocsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEditableDocsValueChanged
        // TODO add your handling code here:
        m_selectedDoc = m_docModels.get(listEditableDocs.getSelectedIndex());
        lbl_SelectedDoc.setText(m_selectedDoc.getName() + " " + m_selectedDoc.getId());
    }//GEN-LAST:event_listEditableDocsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btn_Load;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JComboBox cb_projects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_SelectedDoc;
    private javax.swing.JList listEditableDocs;
    private javax.swing.JTable tableViewableDocs;
    // End of variables declaration//GEN-END:variables

    @Override
    public synchronized void setDocumentModelList(List<DocumentModel> list)
    {
        m_docModels = list;
        
        displayResult();
    }
}
